# Post-processing
# for now assumes all workspace generated by main.R still loaded. 


### Post-processing - log of resources ####
log_resources <- sims %>% get_mon_resources()
#log_resources %>% View()

p<-plot(get_mon_resources(sims), #%>% filter(time>24*60),
        metric = "usage",
        c("ambulance","AEbay"),
        items = c("queue","server"),
        steps=FALSE);p

p2<-plot(get_mon_resources(sims), #%>% filter(time>24*60),
         metric = "usage",
         c("ambulance","AEbay"),
         items = c("queue","server"),
         steps=TRUE);p2

p2<-plot(get_mon_resources(sims), #%>% filter(time>24*60),
         metric = "usage",
         c("ambulance"),
         items = c("queue","server"),
         steps=TRUE);p2

#+
#labs(subtitle = paste0("% pre-handover unavoidable: ",now_prehandoverNAperc*100,"%\n Increment to off-site JCT (min): ",now_JCToffsiteincrement));

plot(log_resources,
     metric="utilization",
     c("ambulance", "AEbay"))



### Post-processing - log of attributes ####
log_attributes <- sims %>% get_mon_attributes()
#log_attributes %>% View()

log_attributes %>%
  filter(key %in% c("T_timetoscene","T_timeatscene","T_timetosite","T_unavprehand","T_timetoclear")) %>%
  group_by(key) %>%
  summarise(median=median(value,na.rm=T),
            mean=mean(value,na.rm=T),
            sd=sd(value,na.rm=T),
            n=n())

log_attributes_w <- log_attributes %>% # remove control vars
  filter(name!="") %>% # to remove globals
  filter(substr(name,1,5)!="Contr") %>% # remove control vars
  dplyr::select(-time) %>%
  pivot_wider(names_from = key,values_from=value)

log_attributes_w <- log_attributes_w %>% mutate(T_allocate = t_ambulanceseized-t_Rclockstart,
                                                T_prehandover = t_EDhandover-t_hospitalarrival,
                                                T_JCT=t_JCTend-t_Rclockstart)

# Empirical JCT by Care Model
log_attributes_w %>% filter(!is.na(Done)) %>% mutate(T_JCT=t_JCTend-t_Rclockstart) %>%
  group_by(Convey) %>%
  summarise(median=median(T_JCT,na.rm=T),
            mean=mean(T_JCT,na.rm=T),
            sd=sd(T_JCT,na.rm=T),
            n=n())

# Empirical JCT overall
log_attributes_w %>% filter(!is.na(Done)) %>% mutate(T_JCT=t_JCTend-t_Rclockstart) %>%
  summarise(median=median(T_JCT,na.rm=T),
            mean=mean(T_JCT,na.rm=T),
            sd=sd(T_JCT,na.rm=T),
            n=n())

log_attributes_w %>% group_by(Convey) %>%
  summarise_at(c("T_allocate","T_prehandover","T_JCT"),list(mean=mean,median=median),na.rm=TRUE)

# Plotting arrivals (ambulance)

log_plot_arrivals <- log_attributes_w %>% dplyr::select(c("replication","Cat","Convey","t_Rclockstart","t_hospitalarrival")) %>%
  #filter(!is.na(Cat)) %>%
  mutate(Cat=ifelse(is.na(Cat),99,Cat),
         Convey=ifelse(is.na(Convey),99,Convey)) %>%
  mutate(time=ifelse(is.na(t_Rclockstart),t_hospitalarrival,t_Rclockstart))

my_step <- 60 # in minutes
log_plot_arrivals <- log_plot_arrivals %>% mutate(step = (time %/% my_step)*my_step )

aux <- log_plot_arrivals %>% group_by(replication,step) %>%
  summarise(n=n())


ggplot(data=aux,aes(x=step,y=n,colour=as.factor(replication)))+
  geom_step()

ggplot()+
  geom_col(data=aux,aes(x=step,y=n / (my_step/60),fill=as.factor(replication))) +
  geom_line(data=df_demand_sch,aes(x=Time,y=Incident_Demand+Direct_Demand))+
  facet_wrap(~replication,ncol=1)+
  labs(title="Calls being made",x="Time (days)",y="Nr/hour (step time window)")+
  theme(axis.text.x = element_text(angle = 0),text = element_text(size=10))+
  scale_x_discrete(breaks = round(seq(min(aux$step), max(aux$step), by = 1440),1),
                   labels = seq(0,13,1))

# by category
aux2 <- log_plot_arrivals %>% group_by(replication,step,Cat) %>%
  summarise(n=n())


ggplot()+
  geom_col(data=aux2,aes(x=step,y=n / (my_step/60),fill=as.factor(Cat))) +
  geom_line(data=df_demand_sch,aes(x=Time,y=Incident_Demand+Direct_Demand))+
  facet_wrap(~replication,ncol=1)+
  labs(title="Calls being made by Category",x="Time (days)",y="Nr/hour (step time window)")+
  theme(axis.text.x = element_text(angle = 0),text = element_text(size=10))+
  scale_x_discrete(breaks = round(seq(min(aux$step), max(aux$step), by = 1440),1),
                   labels = seq(0,13,1))


ggplot()+
  geom_col(data=aux2 %>% filter(Cat!=99),aes(x=step,y=n / (my_step/60),fill=as.factor(Cat))) +
  #geom_line(data=df_demand_sch,aes(x=Time,y=Incident_Demand))+
  geom_line(data=df_DSA_sch,aes(x=Time,y=DSV_Enforced))+
  facet_wrap(~replication,ncol=1)+
  labs(title="Calls being made by Category, overlay supply schedule",x="Time (days)",y="Nr/hour (step time window)")+
  theme(axis.text.x = element_text(angle = 0),text = element_text(size=10))+
  scale_x_discrete(breaks = round(seq(min(aux$step), max(aux$step), by = 1440),1),
                   labels = seq(0,13,1))

# by care model
aux2 <- log_plot_arrivals %>% group_by(replication,step,Convey) %>%
  summarise(n=n())


ggplot()+
  geom_col(data=aux2,aes(x=step,y=n / (my_step/60),fill=as.factor(Convey))) +
  geom_line(data=df_demand_sch,aes(x=Time,y=Incident_Demand+Direct_Demand))+
  facet_wrap(~replication,ncol=1)+
  labs(title="Calls being made by Conveyance",x="Time (days)",y="Nr/hour (step time window)")+
  theme(axis.text.x = element_text(angle = 0),text = element_text(size=10))+
  scale_x_discrete(breaks = round(seq(min(aux$step), max(aux$step), by = 1440),1),
                   labels = seq(0,13,1))


aux2$Convey <- factor(aux2$Convey,rev(unique(aux2$Convey)))

ggplot()+
  geom_col(data=aux2 %>% filter(Convey!=99),aes(x=step,y=n / (my_step/60),fill=as.factor(Convey))) +
  #geom_line(data=df_demand_sch,aes(x=Time,y=Incident_Demand))+
  geom_line(data=df_DSA_sch,aes(x=Time,y=DSV_Enforced))+
  facet_wrap(~replication,ncol=1)+
  labs(title="Calls being made by Conveyance, overlay supply schedule",x="Time (days)",y="Nr/hour (step time window)")+
  theme(axis.text.x = element_text(angle = 0),text = element_text(size=10))+
  scale_x_discrete(breaks = round(seq(min(aux$step), max(aux$step), by = 1440),1),
                   labels = seq(0,13,1))

# by category and care model (across replications)
aux3 <- log_plot_arrivals %>% group_by(step,Cat,Convey) %>%
  summarise(n=n())


ggplot()+
  geom_col(data=aux3,aes(x=step,y=n / (my_step/60),fill=as.factor(Convey))) +
  #geom_line(data=df_demand_sch,aes(x=Time,y=Demand))+
  facet_wrap(~Cat,ncol=1)+
  labs(title="Calls being made by Conveyance",x="Time (days)",y="Nr/hour (step time window)")+
  theme(axis.text.x = element_text(angle = 0),text = element_text(size=10))+
  scale_x_discrete(breaks = round(seq(min(aux$step), max(aux$step), by = 1440),1),
                   labels = seq(0,13,1))

### Post-processing - log of arrivals ####
log_arrivals <- sims %>% get_mon_arrivals()

plot(log_arrivals,
     metric="waiting_time",
     resources=c(c("ambulance", "AEbay")))

plot(log_arrivals,
     metric="flow_time",
     resources=c(c("ambulance", "AEbay")))

#log_arrivals %>% View()
log_arrivals %>% filter(activity_time!=0) %>% summarise(median=median(activity_time,na.rm=T),
                                                        mean=mean(activity_time,na.rm=T),
                                                        sd=sd(activity_time,na.rm=T),
                                                        n=n())

log_arrivals %>% filter(activity_time!=0,start_time<(7*24*60)) %>% summarise(median=median(activity_time,na.rm=T),
                                                                             mean=mean(activity_time,na.rm=T),
                                                                             sd=sd(activity_time,na.rm=T),
                                                                             n=n())



